package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource/identityschema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

func BrazeSDKAuthenticationKeysResourceIdentitySchema() identityschema.Schema {
	return identityschema.Schema{
		Attributes: map[string]identityschema.Attribute{
			"app_id": identityschema.StringAttribute{RequiredForImport: true},
		},
	}
}

func BrazeSDKAuthenticationKeysResourceSchema(_ context.Context) schema.Schema {
	return schema.Schema{
		Description: "Exclusively manage the full SDK Authentication key collection for one Braze app. Use resource `for_each` to manage multiple apps within an app group; the API `app_group` path prefix does not change this per-app scope. Remote keys omitted from configuration are removed on apply. Do not manage the same app's keys with singular resources, another collection resource, or another Terraform state. The provider REST API key needs the `sdk_authentication.create`, `sdk_authentication.keys`, `sdk_authentication.primary`, and `sdk_authentication.delete` permissions. This resource registers public keys; it does not manage private keys or SDK Authentication enforcement.\n\nDestroy relinquishes management and retains all remote keys. Changing `app_id` replaces the management resource and leaves the old app's keys intact. An app with existing keys must be imported before management begins.\n\nBraze permits at most three keys per app and does not allow deletion of the primary key. The provider orders changes to complete in one apply where possible, promoting only the configured final primary. A plan that requires a temporary primary is rejected: explicitly promote a surviving key in a preceding apply or retire an unwanted non-primary key first. For controlled rotation, add the next key, select it as primary when appropriate, migrate JWT issuers while both keys remain, then remove the previous key. The provider cannot determine whether issuer migration or JWT expiry is complete.\n\nIf initial creation partially fails, confirmed key IDs are retained in state and Terraform may taint the resource. Inspect the remote collection and state, resolve the error, then deliberately untaint and refresh/apply, or relinquish the state entry and import the app again. Replacement retains keys and refuses to create over an occupied collection, so it is not automatic recovery. A lost create response requires manual reconciliation before another apply; creation cannot be guaranteed exactly once across failures.",
		Attributes: map[string]schema.Attribute{
			"app_id": schema.StringAttribute{
				Description: "The Braze app API identifier. Changes replace the management resource and retain all keys in the previous app.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"keys": schema.SetNestedAttribute{
				Description: "The complete desired collection of one to three keys. Exactly one member must be primary. Members match existing keys by the exact public key and description; changing either creates a new key and retires the old one. Duplicate descriptions are allowed with distinct public keys, but duplicate public-key/description pairs are ambiguous and rejected. Existing ambiguous duplicates require explicit resolution before reconciliation.",
				Required:    true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Description: "The key ID generated by Braze. Use app-ID import to adopt an existing collection; do not configure member IDs.",
							Computed:    true,
						},
						"rsa_public_key": schema.StringAttribute{
							Description: "The non-empty RSA public key in PEM format. Changes replace this member, preserving other members' IDs.",
							Required:    true,
						},
						"description": schema.StringAttribute{
							Description: "A non-empty description. Changes replace this member. Import preserves remotely empty descriptions verbatim, but such a key needs a replacement with a description to satisfy this configuration contract.",
							Required:    true,
						},
						"primary": schema.BoolAttribute{
							Description: "Whether this member must be primary. Exactly one member must be true. Changing the designation promotes the selected existing key without recreating it.",
							Required:    true,
						},
					},
				},
			},
		},
	}
}
