// Code generated by ogen, DO NOT EDIT.

package brazeclient

// setDefaults set default value of fields.
func (s *CreateContentBlockRequest) setDefaults() {
	{
		val := CreateContentBlockRequestState("active")
		s.State.SetTo(val)
	}
}
