// Code generated by ogen, DO NOT EDIT.

package brazeclient

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateContentBlockOperation   OperationName = "CreateContentBlock"
	CreateEmailTemplateOperation  OperationName = "CreateEmailTemplate"
	GetContentBlockInfoOperation  OperationName = "GetContentBlockInfo"
	GetEmailTemplateInfoOperation OperationName = "GetEmailTemplateInfo"
	ListContentBlocksOperation    OperationName = "ListContentBlocks"
	ListEmailTemplatesOperation   OperationName = "ListEmailTemplates"
	UpdateContentBlockOperation   OperationName = "UpdateContentBlock"
	UpdateEmailTemplateOperation  OperationName = "UpdateEmailTemplate"
)
