// Code generated by ogen, DO NOT EDIT.

package brazeclient

import (
	"net/http"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetContentBlockInfoParams is parameters of getContentBlockInfo operation.
type GetContentBlockInfoParams struct {
	// Content Block identifier.
	ContentBlockID string
	// When set to true, returns Message Variation API identifiers where this Content Block is included.
	IncludeInclusionData OptBool `json:",omitempty,omitzero"`
}

func unpackGetContentBlockInfoParams(packed middleware.Parameters) (params GetContentBlockInfoParams) {
	{
		key := middleware.ParameterKey{
			Name: "content_block_id",
			In:   "query",
		}
		params.ContentBlockID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "include_inclusion_data",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeInclusionData = v.(OptBool)
		}
	}
	return params
}

func decodeGetContentBlockInfoParams(args [0]string, argsEscaped bool, r *http.Request) (params GetContentBlockInfoParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: content_block_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "content_block_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ContentBlockID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "content_block_id",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: include_inclusion_data.
	{
		val := bool(false)
		params.IncludeInclusionData.SetTo(val)
	}
	// Decode query: include_inclusion_data.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_inclusion_data",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeInclusionDataVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeInclusionDataVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeInclusionData.SetTo(paramsDotIncludeInclusionDataVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_inclusion_data",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ListContentBlocksParams is parameters of listContentBlocks operation.
type ListContentBlocksParams struct {
	// Retrieve only Content Blocks updated at or after the given time.
	ModifiedAfter OptDateTime `json:",omitempty,omitzero"`
	// Retrieve only Content Blocks updated at or before the given time.
	ModifiedBefore OptDateTime `json:",omitempty,omitzero"`
	// Maximum number of Content Blocks to retrieve (default 100, max 1000).
	Limit OptInt `json:",omitempty,omitzero"`
	// Number of Content Blocks to skip before returning results.
	Offset OptInt `json:",omitempty,omitzero"`
}

func unpackListContentBlocksParams(packed middleware.Parameters) (params ListContentBlocksParams) {
	{
		key := middleware.ParameterKey{
			Name: "modified_after",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ModifiedAfter = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "modified_before",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ModifiedBefore = v.(OptDateTime)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "limit",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Limit = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "offset",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Offset = v.(OptInt)
		}
	}
	return params
}

func decodeListContentBlocksParams(args [0]string, argsEscaped bool, r *http.Request) (params ListContentBlocksParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: modified_after.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "modified_after",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotModifiedAfterVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotModifiedAfterVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ModifiedAfter.SetTo(paramsDotModifiedAfterVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "modified_after",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: modified_before.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "modified_before",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotModifiedBeforeVal time.Time
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToDateTime(val)
					if err != nil {
						return err
					}

					paramsDotModifiedBeforeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ModifiedBefore.SetTo(paramsDotModifiedBeforeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "modified_before",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: limit.
	{
		val := int(100)
		params.Limit.SetTo(val)
	}
	// Decode query: limit.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotLimitVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotLimitVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Limit.SetTo(paramsDotLimitVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Limit.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           1,
							MaxSet:        true,
							Max:           1000,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "limit",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: offset.
	{
		val := int(0)
		params.Offset.SetTo(val)
	}
	// Decode query: offset.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotOffsetVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotOffsetVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Offset.SetTo(paramsDotOffsetVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Offset.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        false,
							Max:           0,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "offset",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
