// Code generated by ogen, DO NOT EDIT.

package brazeclient

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBrazeApiKey handles brazeApiKey security.
	HandleBrazeApiKey(ctx context.Context, operationName OperationName, t BrazeApiKey) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesBrazeApiKey = map[string][]string{
	CreateContentBlockOperation:  []string{},
	GetContentBlockInfoOperation: []string{},
	ListContentBlocksOperation:   []string{},
	UpdateContentBlockOperation:  []string{},
}

func (s *Server) securityBrazeApiKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BrazeApiKey
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBrazeApiKey[operationName]
	rctx, err := s.sec.HandleBrazeApiKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BrazeApiKey provides brazeApiKey security value.
	BrazeApiKey(ctx context.Context, operationName OperationName, client *Client) (BrazeApiKey, error)
}

func (s *Client) securityBrazeApiKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BrazeApiKey(ctx, operationName, s)
	if err != nil {
		return errors.Wrap(err, "security source \"BrazeApiKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
