// Code generated by ogen, DO NOT EDIT.

package brazeclient

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCatalogOperation                  OperationName = "CreateCatalog"
	CreateCatalogItemOperation              OperationName = "CreateCatalogItem"
	CreateContentBlockOperation             OperationName = "CreateContentBlock"
	CreateEmailTemplateOperation            OperationName = "CreateEmailTemplate"
	CreateSDKAuthenticationKeyOperation     OperationName = "CreateSDKAuthenticationKey"
	DeleteCatalogOperation                  OperationName = "DeleteCatalog"
	DeleteCatalogItemOperation              OperationName = "DeleteCatalogItem"
	DeleteSDKAuthenticationKeyOperation     OperationName = "DeleteSDKAuthenticationKey"
	GetCatalogItemOperation                 OperationName = "GetCatalogItem"
	GetContentBlockInfoOperation            OperationName = "GetContentBlockInfo"
	GetEmailTemplateInfoOperation           OperationName = "GetEmailTemplateInfo"
	ListCatalogItemsOperation               OperationName = "ListCatalogItems"
	ListCatalogsOperation                   OperationName = "ListCatalogs"
	ListContentBlocksOperation              OperationName = "ListContentBlocks"
	ListEmailTemplatesOperation             OperationName = "ListEmailTemplates"
	ListSDKAuthenticationKeysOperation      OperationName = "ListSDKAuthenticationKeys"
	ReplaceCatalogItemOperation             OperationName = "ReplaceCatalogItem"
	SetPrimarySDKAuthenticationKeyOperation OperationName = "SetPrimarySDKAuthenticationKey"
	UpdateContentBlockOperation             OperationName = "UpdateContentBlock"
	UpdateEmailTemplateOperation            OperationName = "UpdateEmailTemplate"
)
