// Code generated by ogen, DO NOT EDIT.

package brazeclient

import (
	"context"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CreateCatalog invokes createCatalog operation.
	//
	// Create catalog.
	//
	// POST /catalogs
	CreateCatalog(ctx context.Context, request *CreateCatalogRequest) (*CreateCatalogResponse, error)
	// CreateCatalogItem invokes createCatalogItem operation.
	//
	// Create catalog item.
	//
	// POST /catalogs/{catalog_name}/items/{item_id}
	CreateCatalogItem(ctx context.Context, request *CreateCatalogItemRequest, params CreateCatalogItemParams) (*CatalogItemOperationResponse, error)
	// CreateContentBlock invokes createContentBlock operation.
	//
	// Create a Content Block on the Braze dashboard.
	//
	// POST /content_blocks/create
	CreateContentBlock(ctx context.Context, request *CreateContentBlockRequest) (*CreateContentBlockResponse, error)
	// CreateEmailTemplate invokes createEmailTemplate operation.
	//
	// Create an Email Template on the Braze dashboard.
	//
	// POST /templates/email/create
	CreateEmailTemplate(ctx context.Context, request *CreateEmailTemplateRequest) (*CreateEmailTemplateResponse, error)
	// DeleteCatalog invokes deleteCatalog operation.
	//
	// Delete catalog.
	//
	// DELETE /catalogs/{catalog_name}
	DeleteCatalog(ctx context.Context, params DeleteCatalogParams) (*DeleteCatalogResponse, error)
	// DeleteCatalogItem invokes deleteCatalogItem operation.
	//
	// Delete catalog item.
	//
	// DELETE /catalogs/{catalog_name}/items/{item_id}
	DeleteCatalogItem(ctx context.Context, params DeleteCatalogItemParams) (*DeleteCatalogItemResponse, error)
	// GetCatalogItem invokes getCatalogItem operation.
	//
	// Get catalog item.
	//
	// GET /catalogs/{catalog_name}/items/{item_id}
	GetCatalogItem(ctx context.Context, params GetCatalogItemParams) (*GetCatalogItemResponse, error)
	// GetContentBlockInfo invokes getContentBlockInfo operation.
	//
	// Call information for your existing Content Blocks.
	//
	// GET /content_blocks/info
	GetContentBlockInfo(ctx context.Context, params GetContentBlockInfoParams) (*GetContentBlockInfoResponse, error)
	// GetEmailTemplateInfo invokes getEmailTemplateInfo operation.
	//
	// Call information for your existing Email Templates.
	//
	// GET /templates/email/info
	GetEmailTemplateInfo(ctx context.Context, params GetEmailTemplateInfoParams) (*GetEmailTemplateInfoResponse, error)
	// ListCatalogItems invokes listCatalogItems operation.
	//
	// List catalog items.
	//
	// GET /catalogs/{catalog_name}/items
	ListCatalogItems(ctx context.Context, params ListCatalogItemsParams) (*ListCatalogItemsResponseHeaders, error)
	// ListCatalogs invokes listCatalogs operation.
	//
	// List catalogs.
	//
	// GET /catalogs
	ListCatalogs(ctx context.Context) (*ListCatalogsResponse, error)
	// ListContentBlocks invokes listContentBlocks operation.
	//
	// List your existing Content Blocks information.
	//
	// GET /content_blocks/list
	ListContentBlocks(ctx context.Context, params ListContentBlocksParams) (*ListContentBlocksResponse, error)
	// ListEmailTemplates invokes listEmailTemplates operation.
	//
	// List your existing Email Templates information.
	//
	// GET /templates/email/list
	ListEmailTemplates(ctx context.Context, params ListEmailTemplatesParams) (*ListEmailTemplatesResponse, error)
	// ReplaceCatalogItem invokes replaceCatalogItem operation.
	//
	// Replace catalog item.
	//
	// PUT /catalogs/{catalog_name}/items/{item_id}
	ReplaceCatalogItem(ctx context.Context, request *ReplaceCatalogItemRequest, params ReplaceCatalogItemParams) (*CatalogItemOperationResponse, error)
	// UpdateContentBlock invokes updateContentBlock operation.
	//
	// Update a Content Block on the Braze dashboard.
	//
	// POST /content_blocks/update
	UpdateContentBlock(ctx context.Context, request *UpdateContentBlockRequest) (UpdateContentBlockRes, error)
	// UpdateEmailTemplate invokes updateEmailTemplate operation.
	//
	// Update an Email Template on the Braze dashboard.
	//
	// POST /templates/email/update
	UpdateEmailTemplate(ctx context.Context, request *UpdateEmailTemplateRequest) (*UpdateEmailTemplateResponse, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// CreateCatalog invokes createCatalog operation.
//
// Create catalog.
//
// POST /catalogs
func (c *Client) CreateCatalog(ctx context.Context, request *CreateCatalogRequest) (*CreateCatalogResponse, error) {
	res, err := c.sendCreateCatalog(ctx, request)
	return res, err
}

func (c *Client) sendCreateCatalog(ctx context.Context, request *CreateCatalogRequest) (res *CreateCatalogResponse, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/catalogs"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateCatalogRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, CreateCatalogOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeCreateCatalogResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateCatalogItem invokes createCatalogItem operation.
//
// Create catalog item.
//
// POST /catalogs/{catalog_name}/items/{item_id}
func (c *Client) CreateCatalogItem(ctx context.Context, request *CreateCatalogItemRequest, params CreateCatalogItemParams) (*CatalogItemOperationResponse, error) {
	res, err := c.sendCreateCatalogItem(ctx, request, params)
	return res, err
}

func (c *Client) sendCreateCatalogItem(ctx context.Context, request *CreateCatalogItemRequest, params CreateCatalogItemParams) (res *CatalogItemOperationResponse, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/catalogs/"
	{
		// Encode "catalog_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "catalog_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CatalogName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/items/"
	{
		// Encode "item_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "item_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ItemID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateCatalogItemRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, CreateCatalogItemOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeCreateCatalogItemResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateContentBlock invokes createContentBlock operation.
//
// Create a Content Block on the Braze dashboard.
//
// POST /content_blocks/create
func (c *Client) CreateContentBlock(ctx context.Context, request *CreateContentBlockRequest) (*CreateContentBlockResponse, error) {
	res, err := c.sendCreateContentBlock(ctx, request)
	return res, err
}

func (c *Client) sendCreateContentBlock(ctx context.Context, request *CreateContentBlockRequest) (res *CreateContentBlockResponse, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/content_blocks/create"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateContentBlockRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, CreateContentBlockOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeCreateContentBlockResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// CreateEmailTemplate invokes createEmailTemplate operation.
//
// Create an Email Template on the Braze dashboard.
//
// POST /templates/email/create
func (c *Client) CreateEmailTemplate(ctx context.Context, request *CreateEmailTemplateRequest) (*CreateEmailTemplateResponse, error) {
	res, err := c.sendCreateEmailTemplate(ctx, request)
	return res, err
}

func (c *Client) sendCreateEmailTemplate(ctx context.Context, request *CreateEmailTemplateRequest) (res *CreateEmailTemplateResponse, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/templates/email/create"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateEmailTemplateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, CreateEmailTemplateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeCreateEmailTemplateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteCatalog invokes deleteCatalog operation.
//
// Delete catalog.
//
// DELETE /catalogs/{catalog_name}
func (c *Client) DeleteCatalog(ctx context.Context, params DeleteCatalogParams) (*DeleteCatalogResponse, error) {
	res, err := c.sendDeleteCatalog(ctx, params)
	return res, err
}

func (c *Client) sendDeleteCatalog(ctx context.Context, params DeleteCatalogParams) (res *DeleteCatalogResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/catalogs/"
	{
		// Encode "catalog_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "catalog_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CatalogName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, DeleteCatalogOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeDeleteCatalogResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// DeleteCatalogItem invokes deleteCatalogItem operation.
//
// Delete catalog item.
//
// DELETE /catalogs/{catalog_name}/items/{item_id}
func (c *Client) DeleteCatalogItem(ctx context.Context, params DeleteCatalogItemParams) (*DeleteCatalogItemResponse, error) {
	res, err := c.sendDeleteCatalogItem(ctx, params)
	return res, err
}

func (c *Client) sendDeleteCatalogItem(ctx context.Context, params DeleteCatalogItemParams) (res *DeleteCatalogItemResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/catalogs/"
	{
		// Encode "catalog_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "catalog_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CatalogName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/items/"
	{
		// Encode "item_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "item_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ItemID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, DeleteCatalogItemOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeDeleteCatalogItemResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetCatalogItem invokes getCatalogItem operation.
//
// Get catalog item.
//
// GET /catalogs/{catalog_name}/items/{item_id}
func (c *Client) GetCatalogItem(ctx context.Context, params GetCatalogItemParams) (*GetCatalogItemResponse, error) {
	res, err := c.sendGetCatalogItem(ctx, params)
	return res, err
}

func (c *Client) sendGetCatalogItem(ctx context.Context, params GetCatalogItemParams) (res *GetCatalogItemResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/catalogs/"
	{
		// Encode "catalog_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "catalog_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CatalogName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/items/"
	{
		// Encode "item_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "item_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ItemID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, GetCatalogItemOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeGetCatalogItemResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetContentBlockInfo invokes getContentBlockInfo operation.
//
// Call information for your existing Content Blocks.
//
// GET /content_blocks/info
func (c *Client) GetContentBlockInfo(ctx context.Context, params GetContentBlockInfoParams) (*GetContentBlockInfoResponse, error) {
	res, err := c.sendGetContentBlockInfo(ctx, params)
	return res, err
}

func (c *Client) sendGetContentBlockInfo(ctx context.Context, params GetContentBlockInfoParams) (res *GetContentBlockInfoResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/content_blocks/info"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "content_block_id" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "content_block_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.ContentBlockID))
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "include_inclusion_data" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "include_inclusion_data",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.IncludeInclusionData.Get(); ok {
				return e.EncodeValue(conv.BoolToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, GetContentBlockInfoOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeGetContentBlockInfoResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetEmailTemplateInfo invokes getEmailTemplateInfo operation.
//
// Call information for your existing Email Templates.
//
// GET /templates/email/info
func (c *Client) GetEmailTemplateInfo(ctx context.Context, params GetEmailTemplateInfoParams) (*GetEmailTemplateInfoResponse, error) {
	res, err := c.sendGetEmailTemplateInfo(ctx, params)
	return res, err
}

func (c *Client) sendGetEmailTemplateInfo(ctx context.Context, params GetEmailTemplateInfoParams) (res *GetEmailTemplateInfoResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/templates/email/info"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "email_template_id" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "email_template_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			return e.EncodeValue(conv.StringToString(params.EmailTemplateID))
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, GetEmailTemplateInfoOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeGetEmailTemplateInfoResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListCatalogItems invokes listCatalogItems operation.
//
// List catalog items.
//
// GET /catalogs/{catalog_name}/items
func (c *Client) ListCatalogItems(ctx context.Context, params ListCatalogItemsParams) (*ListCatalogItemsResponseHeaders, error) {
	res, err := c.sendListCatalogItems(ctx, params)
	return res, err
}

func (c *Client) sendListCatalogItems(ctx context.Context, params ListCatalogItemsParams) (res *ListCatalogItemsResponseHeaders, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/catalogs/"
	{
		// Encode "catalog_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "catalog_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CatalogName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/items"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "cursor" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Cursor.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, ListCatalogItemsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListCatalogItemsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListCatalogs invokes listCatalogs operation.
//
// List catalogs.
//
// GET /catalogs
func (c *Client) ListCatalogs(ctx context.Context) (*ListCatalogsResponse, error) {
	res, err := c.sendListCatalogs(ctx)
	return res, err
}

func (c *Client) sendListCatalogs(ctx context.Context) (res *ListCatalogsResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/catalogs"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, ListCatalogsOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListCatalogsResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListContentBlocks invokes listContentBlocks operation.
//
// List your existing Content Blocks information.
//
// GET /content_blocks/list
func (c *Client) ListContentBlocks(ctx context.Context, params ListContentBlocksParams) (*ListContentBlocksResponse, error) {
	res, err := c.sendListContentBlocks(ctx, params)
	return res, err
}

func (c *Client) sendListContentBlocks(ctx context.Context, params ListContentBlocksParams) (res *ListContentBlocksResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/content_blocks/list"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "modified_after" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "modified_after",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.ModifiedAfter.Get(); ok {
				return e.EncodeValue(conv.DateTimeToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "modified_before" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "modified_before",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.ModifiedBefore.Get(); ok {
				return e.EncodeValue(conv.DateTimeToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "offset" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Offset.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, ListContentBlocksOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListContentBlocksResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListEmailTemplates invokes listEmailTemplates operation.
//
// List your existing Email Templates information.
//
// GET /templates/email/list
func (c *Client) ListEmailTemplates(ctx context.Context, params ListEmailTemplatesParams) (*ListEmailTemplatesResponse, error) {
	res, err := c.sendListEmailTemplates(ctx, params)
	return res, err
}

func (c *Client) sendListEmailTemplates(ctx context.Context, params ListEmailTemplatesParams) (res *ListEmailTemplatesResponse, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/templates/email/list"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "modified_after" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "modified_after",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.ModifiedAfter.Get(); ok {
				return e.EncodeValue(conv.DateTimeToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "modified_before" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "modified_before",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.ModifiedBefore.Get(); ok {
				return e.EncodeValue(conv.DateTimeToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "offset" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "offset",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Offset.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, ListEmailTemplatesOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeListEmailTemplatesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ReplaceCatalogItem invokes replaceCatalogItem operation.
//
// Replace catalog item.
//
// PUT /catalogs/{catalog_name}/items/{item_id}
func (c *Client) ReplaceCatalogItem(ctx context.Context, request *ReplaceCatalogItemRequest, params ReplaceCatalogItemParams) (*CatalogItemOperationResponse, error) {
	res, err := c.sendReplaceCatalogItem(ctx, request, params)
	return res, err
}

func (c *Client) sendReplaceCatalogItem(ctx context.Context, request *ReplaceCatalogItemRequest, params ReplaceCatalogItemParams) (res *CatalogItemOperationResponse, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [4]string
	pathParts[0] = "/catalogs/"
	{
		// Encode "catalog_name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "catalog_name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.CatalogName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/items/"
	{
		// Encode "item_id" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "item_id",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ItemID))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeReplaceCatalogItemRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, ReplaceCatalogItemOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeReplaceCatalogItemResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UpdateContentBlock invokes updateContentBlock operation.
//
// Update a Content Block on the Braze dashboard.
//
// POST /content_blocks/update
func (c *Client) UpdateContentBlock(ctx context.Context, request *UpdateContentBlockRequest) (UpdateContentBlockRes, error) {
	res, err := c.sendUpdateContentBlock(ctx, request)
	return res, err
}

func (c *Client) sendUpdateContentBlock(ctx context.Context, request *UpdateContentBlockRequest) (res UpdateContentBlockRes, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/content_blocks/update"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUpdateContentBlockRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, UpdateContentBlockOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeUpdateContentBlockResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// UpdateEmailTemplate invokes updateEmailTemplate operation.
//
// Update an Email Template on the Braze dashboard.
//
// POST /templates/email/update
func (c *Client) UpdateEmailTemplate(ctx context.Context, request *UpdateEmailTemplateRequest) (*UpdateEmailTemplateResponse, error) {
	res, err := c.sendUpdateEmailTemplate(ctx, request)
	return res, err
}

func (c *Client) sendUpdateEmailTemplate(ctx context.Context, request *UpdateEmailTemplateRequest) (res *UpdateEmailTemplateResponse, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/templates/email/update"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeUpdateEmailTemplateRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	{
		type bitset = [1]uint8
		var satisfied bitset
		{

			switch err := c.securityBrazeApiKey(ctx, UpdateEmailTemplateOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BrazeApiKey\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	result, err := decodeUpdateEmailTemplateResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
