// Code generated by ogen, DO NOT EDIT.

package brazeclient

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateContentBlockOperation  OperationName = "CreateContentBlock"
	GetContentBlockInfoOperation OperationName = "GetContentBlockInfo"
	ListContentBlocksOperation   OperationName = "ListContentBlocks"
	UpdateContentBlockOperation  OperationName = "UpdateContentBlock"
)
