// Code generated by ogen, DO NOT EDIT.

package brazeclient

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BrazeApiKey struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BrazeApiKey) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BrazeApiKey) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BrazeApiKey) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BrazeApiKey) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/CreateContentBlockRequest
type CreateContentBlockRequest struct {
	// Name of the Content Block. Must be less than 100 characters.
	Name string `json:"name"`
	// Description of the Content Block. Must be less than 250 characters.
	Description OptString `json:"description"`
	// HTML or text content within Content Block.
	Content string `json:"content"`
	// Choose active or draft. Defaults to active if not specified.
	State OptCreateContentBlockRequestState `json:"state"`
	// Tags must already exist.
	Tags []string `json:"tags"`
}

// GetName returns the value of Name.
func (s *CreateContentBlockRequest) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateContentBlockRequest) GetDescription() OptString {
	return s.Description
}

// GetContent returns the value of Content.
func (s *CreateContentBlockRequest) GetContent() string {
	return s.Content
}

// GetState returns the value of State.
func (s *CreateContentBlockRequest) GetState() OptCreateContentBlockRequestState {
	return s.State
}

// GetTags returns the value of Tags.
func (s *CreateContentBlockRequest) GetTags() []string {
	return s.Tags
}

// SetName sets the value of Name.
func (s *CreateContentBlockRequest) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateContentBlockRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetContent sets the value of Content.
func (s *CreateContentBlockRequest) SetContent(val string) {
	s.Content = val
}

// SetState sets the value of State.
func (s *CreateContentBlockRequest) SetState(val OptCreateContentBlockRequestState) {
	s.State = val
}

// SetTags sets the value of Tags.
func (s *CreateContentBlockRequest) SetTags(val []string) {
	s.Tags = val
}

// Choose active or draft. Defaults to active if not specified.
type CreateContentBlockRequestState string

const (
	CreateContentBlockRequestStateActive CreateContentBlockRequestState = "active"
	CreateContentBlockRequestStateDraft  CreateContentBlockRequestState = "draft"
)

// AllValues returns all CreateContentBlockRequestState values.
func (CreateContentBlockRequestState) AllValues() []CreateContentBlockRequestState {
	return []CreateContentBlockRequestState{
		CreateContentBlockRequestStateActive,
		CreateContentBlockRequestStateDraft,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateContentBlockRequestState) MarshalText() ([]byte, error) {
	switch s {
	case CreateContentBlockRequestStateActive:
		return []byte(s), nil
	case CreateContentBlockRequestStateDraft:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateContentBlockRequestState) UnmarshalText(data []byte) error {
	switch CreateContentBlockRequestState(data) {
	case CreateContentBlockRequestStateActive:
		*s = CreateContentBlockRequestStateActive
		return nil
	case CreateContentBlockRequestStateDraft:
		*s = CreateContentBlockRequestStateDraft
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/CreateContentBlockResponse
type CreateContentBlockResponse struct {
	// Your newly generated block ID.
	ContentBlockID string `json:"content_block_id"`
	// Success message.
	Message string `json:"message"`
}

// GetContentBlockID returns the value of ContentBlockID.
func (s *CreateContentBlockResponse) GetContentBlockID() string {
	return s.ContentBlockID
}

// GetMessage returns the value of Message.
func (s *CreateContentBlockResponse) GetMessage() string {
	return s.Message
}

// SetContentBlockID sets the value of ContentBlockID.
func (s *CreateContentBlockResponse) SetContentBlockID(val string) {
	s.ContentBlockID = val
}

// SetMessage sets the value of Message.
func (s *CreateContentBlockResponse) SetMessage(val string) {
	s.Message = val
}

type ErrorResponse struct {
	// Error message describing what went wrong.
	Message string `json:"message"`
	// Array of minor error messages.
	Errors []string `json:"errors"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// GetErrors returns the value of Errors.
func (s *ErrorResponse) GetErrors() []string {
	return s.Errors
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// SetErrors sets the value of Errors.
func (s *ErrorResponse) SetErrors(val []string) {
	s.Errors = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/GetContentBlockInfoResponse
type GetContentBlockInfoResponse struct {
	// The Content Block identifier.
	ContentBlockID string `json:"content_block_id"`
	// The name of the Content Block.
	Name string `json:"name"`
	// The content in the Content Block.
	Content string `json:"content"`
	// The Content Block description.
	Description OptString `json:"description"`
	// An array of tags formatted as strings.
	Tags []string `json:"tags"`
}

// GetContentBlockID returns the value of ContentBlockID.
func (s *GetContentBlockInfoResponse) GetContentBlockID() string {
	return s.ContentBlockID
}

// GetName returns the value of Name.
func (s *GetContentBlockInfoResponse) GetName() string {
	return s.Name
}

// GetContent returns the value of Content.
func (s *GetContentBlockInfoResponse) GetContent() string {
	return s.Content
}

// GetDescription returns the value of Description.
func (s *GetContentBlockInfoResponse) GetDescription() OptString {
	return s.Description
}

// GetTags returns the value of Tags.
func (s *GetContentBlockInfoResponse) GetTags() []string {
	return s.Tags
}

// SetContentBlockID sets the value of ContentBlockID.
func (s *GetContentBlockInfoResponse) SetContentBlockID(val string) {
	s.ContentBlockID = val
}

// SetName sets the value of Name.
func (s *GetContentBlockInfoResponse) SetName(val string) {
	s.Name = val
}

// SetContent sets the value of Content.
func (s *GetContentBlockInfoResponse) SetContent(val string) {
	s.Content = val
}

// SetDescription sets the value of Description.
func (s *GetContentBlockInfoResponse) SetDescription(val OptString) {
	s.Description = val
}

// SetTags sets the value of Tags.
func (s *GetContentBlockInfoResponse) SetTags(val []string) {
	s.Tags = val
}

// Ref: #/ListContentBlocksResponse
type ListContentBlocksResponse struct {
	// The number of Content Blocks returned.
	Count         int                                     `json:"count"`
	ContentBlocks []ListContentBlocksResponseContentBlock `json:"content_blocks"`
}

// GetCount returns the value of Count.
func (s *ListContentBlocksResponse) GetCount() int {
	return s.Count
}

// GetContentBlocks returns the value of ContentBlocks.
func (s *ListContentBlocksResponse) GetContentBlocks() []ListContentBlocksResponseContentBlock {
	return s.ContentBlocks
}

// SetCount sets the value of Count.
func (s *ListContentBlocksResponse) SetCount(val int) {
	s.Count = val
}

// SetContentBlocks sets the value of ContentBlocks.
func (s *ListContentBlocksResponse) SetContentBlocks(val []ListContentBlocksResponseContentBlock) {
	s.ContentBlocks = val
}

// Ref: #/ListContentBlocksResponseContentBlock
type ListContentBlocksResponseContentBlock struct {
	// The Content Block identifier.
	ContentBlockID string `json:"content_block_id"`
	// The name of the Content Block.
	Name string `json:"name"`
	// Tags formatted as strings.
	Tags []string `json:"tags"`
}

// GetContentBlockID returns the value of ContentBlockID.
func (s *ListContentBlocksResponseContentBlock) GetContentBlockID() string {
	return s.ContentBlockID
}

// GetName returns the value of Name.
func (s *ListContentBlocksResponseContentBlock) GetName() string {
	return s.Name
}

// GetTags returns the value of Tags.
func (s *ListContentBlocksResponseContentBlock) GetTags() []string {
	return s.Tags
}

// SetContentBlockID sets the value of ContentBlockID.
func (s *ListContentBlocksResponseContentBlock) SetContentBlockID(val string) {
	s.ContentBlockID = val
}

// SetName sets the value of Name.
func (s *ListContentBlocksResponseContentBlock) SetName(val string) {
	s.Name = val
}

// SetTags sets the value of Tags.
func (s *ListContentBlocksResponseContentBlock) SetTags(val []string) {
	s.Tags = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateContentBlockRequestState returns new OptCreateContentBlockRequestState with value set to v.
func NewOptCreateContentBlockRequestState(v CreateContentBlockRequestState) OptCreateContentBlockRequestState {
	return OptCreateContentBlockRequestState{
		Value: v,
		Set:   true,
	}
}

// OptCreateContentBlockRequestState is optional CreateContentBlockRequestState.
type OptCreateContentBlockRequestState struct {
	Value CreateContentBlockRequestState
	Set   bool
}

// IsSet returns true if OptCreateContentBlockRequestState was set.
func (o OptCreateContentBlockRequestState) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateContentBlockRequestState) Reset() {
	var v CreateContentBlockRequestState
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateContentBlockRequestState) SetTo(v CreateContentBlockRequestState) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateContentBlockRequestState) Get() (v CreateContentBlockRequestState, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateContentBlockRequestState) Or(d CreateContentBlockRequestState) CreateContentBlockRequestState {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateContentBlockRequestState returns new OptUpdateContentBlockRequestState with value set to v.
func NewOptUpdateContentBlockRequestState(v UpdateContentBlockRequestState) OptUpdateContentBlockRequestState {
	return OptUpdateContentBlockRequestState{
		Value: v,
		Set:   true,
	}
}

// OptUpdateContentBlockRequestState is optional UpdateContentBlockRequestState.
type OptUpdateContentBlockRequestState struct {
	Value UpdateContentBlockRequestState
	Set   bool
}

// IsSet returns true if OptUpdateContentBlockRequestState was set.
func (o OptUpdateContentBlockRequestState) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateContentBlockRequestState) Reset() {
	var v UpdateContentBlockRequestState
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateContentBlockRequestState) SetTo(v UpdateContentBlockRequestState) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateContentBlockRequestState) Get() (v UpdateContentBlockRequestState, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateContentBlockRequestState) Or(d UpdateContentBlockRequestState) UpdateContentBlockRequestState {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/UpdateContentBlockRequest
type UpdateContentBlockRequest struct {
	// Content Block's API identifier.
	ContentBlockID string `json:"content_block_id"`
	// Name of the Content Block. Must be less than 100 characters.
	Name OptString `json:"name"`
	// Description of the Content Block. Must be less than 250 characters.
	Description OptString `json:"description"`
	// HTML or text content within Content Block.
	Content OptString `json:"content"`
	// Choose active or draft. Defaults to active if not specified.
	State OptUpdateContentBlockRequestState `json:"state"`
	// Tags must already exist.
	Tags []string `json:"tags"`
}

// GetContentBlockID returns the value of ContentBlockID.
func (s *UpdateContentBlockRequest) GetContentBlockID() string {
	return s.ContentBlockID
}

// GetName returns the value of Name.
func (s *UpdateContentBlockRequest) GetName() OptString {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *UpdateContentBlockRequest) GetDescription() OptString {
	return s.Description
}

// GetContent returns the value of Content.
func (s *UpdateContentBlockRequest) GetContent() OptString {
	return s.Content
}

// GetState returns the value of State.
func (s *UpdateContentBlockRequest) GetState() OptUpdateContentBlockRequestState {
	return s.State
}

// GetTags returns the value of Tags.
func (s *UpdateContentBlockRequest) GetTags() []string {
	return s.Tags
}

// SetContentBlockID sets the value of ContentBlockID.
func (s *UpdateContentBlockRequest) SetContentBlockID(val string) {
	s.ContentBlockID = val
}

// SetName sets the value of Name.
func (s *UpdateContentBlockRequest) SetName(val OptString) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *UpdateContentBlockRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetContent sets the value of Content.
func (s *UpdateContentBlockRequest) SetContent(val OptString) {
	s.Content = val
}

// SetState sets the value of State.
func (s *UpdateContentBlockRequest) SetState(val OptUpdateContentBlockRequestState) {
	s.State = val
}

// SetTags sets the value of Tags.
func (s *UpdateContentBlockRequest) SetTags(val []string) {
	s.Tags = val
}

// Choose active or draft. Defaults to active if not specified.
type UpdateContentBlockRequestState string

const (
	UpdateContentBlockRequestStateActive UpdateContentBlockRequestState = "active"
	UpdateContentBlockRequestStateDraft  UpdateContentBlockRequestState = "draft"
)

// AllValues returns all UpdateContentBlockRequestState values.
func (UpdateContentBlockRequestState) AllValues() []UpdateContentBlockRequestState {
	return []UpdateContentBlockRequestState{
		UpdateContentBlockRequestStateActive,
		UpdateContentBlockRequestStateDraft,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateContentBlockRequestState) MarshalText() ([]byte, error) {
	switch s {
	case UpdateContentBlockRequestStateActive:
		return []byte(s), nil
	case UpdateContentBlockRequestStateDraft:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateContentBlockRequestState) UnmarshalText(data []byte) error {
	switch UpdateContentBlockRequestState(data) {
	case UpdateContentBlockRequestStateActive:
		*s = UpdateContentBlockRequestStateActive
		return nil
	case UpdateContentBlockRequestStateDraft:
		*s = UpdateContentBlockRequestStateDraft
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/UpdateContentBlockResponse
type UpdateContentBlockResponse struct {
	// Your newly generated block ID.
	ContentBlockID string `json:"content_block_id"`
	// Success message.
	Message string `json:"message"`
}

// GetContentBlockID returns the value of ContentBlockID.
func (s *UpdateContentBlockResponse) GetContentBlockID() string {
	return s.ContentBlockID
}

// GetMessage returns the value of Message.
func (s *UpdateContentBlockResponse) GetMessage() string {
	return s.Message
}

// SetContentBlockID sets the value of ContentBlockID.
func (s *UpdateContentBlockResponse) SetContentBlockID(val string) {
	s.ContentBlockID = val
}

// SetMessage sets the value of Message.
func (s *UpdateContentBlockResponse) SetMessage(val string) {
	s.Message = val
}
