// Code generated by ogen, DO NOT EDIT.

package brazeclient

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateCatalog implements createCatalog operation.
	//
	// Create catalog.
	//
	// POST /catalogs
	CreateCatalog(ctx context.Context, req *CreateCatalogRequest) (*CreateCatalogResponse, error)
	// CreateCatalogItem implements createCatalogItem operation.
	//
	// Create catalog item.
	//
	// POST /catalogs/{catalog_name}/items/{item_id}
	CreateCatalogItem(ctx context.Context, req *CreateCatalogItemRequest, params CreateCatalogItemParams) (*CatalogItemOperationResponse, error)
	// CreateContentBlock implements createContentBlock operation.
	//
	// Create a Content Block on the Braze dashboard.
	//
	// POST /content_blocks/create
	CreateContentBlock(ctx context.Context, req *CreateContentBlockRequest) (*CreateContentBlockResponse, error)
	// CreateEmailTemplate implements createEmailTemplate operation.
	//
	// Create an Email Template on the Braze dashboard.
	//
	// POST /templates/email/create
	CreateEmailTemplate(ctx context.Context, req *CreateEmailTemplateRequest) (*CreateEmailTemplateResponse, error)
	// DeleteCatalog implements deleteCatalog operation.
	//
	// Delete catalog.
	//
	// DELETE /catalogs/{catalog_name}
	DeleteCatalog(ctx context.Context, params DeleteCatalogParams) (*DeleteCatalogResponse, error)
	// DeleteCatalogItem implements deleteCatalogItem operation.
	//
	// Delete catalog item.
	//
	// DELETE /catalogs/{catalog_name}/items/{item_id}
	DeleteCatalogItem(ctx context.Context, params DeleteCatalogItemParams) (*DeleteCatalogItemResponse, error)
	// GetCatalogItem implements getCatalogItem operation.
	//
	// Get catalog item.
	//
	// GET /catalogs/{catalog_name}/items/{item_id}
	GetCatalogItem(ctx context.Context, params GetCatalogItemParams) (*GetCatalogItemResponse, error)
	// GetContentBlockInfo implements getContentBlockInfo operation.
	//
	// Call information for your existing Content Blocks.
	//
	// GET /content_blocks/info
	GetContentBlockInfo(ctx context.Context, params GetContentBlockInfoParams) (*GetContentBlockInfoResponse, error)
	// GetEmailTemplateInfo implements getEmailTemplateInfo operation.
	//
	// Call information for your existing Email Templates.
	//
	// GET /templates/email/info
	GetEmailTemplateInfo(ctx context.Context, params GetEmailTemplateInfoParams) (*GetEmailTemplateInfoResponse, error)
	// ListCatalogItems implements listCatalogItems operation.
	//
	// List catalog items.
	//
	// GET /catalogs/{catalog_name}/items
	ListCatalogItems(ctx context.Context, params ListCatalogItemsParams) (*ListCatalogItemsResponseHeaders, error)
	// ListCatalogs implements listCatalogs operation.
	//
	// List catalogs.
	//
	// GET /catalogs
	ListCatalogs(ctx context.Context) (*ListCatalogsResponse, error)
	// ListContentBlocks implements listContentBlocks operation.
	//
	// List your existing Content Blocks information.
	//
	// GET /content_blocks/list
	ListContentBlocks(ctx context.Context, params ListContentBlocksParams) (*ListContentBlocksResponse, error)
	// ListEmailTemplates implements listEmailTemplates operation.
	//
	// List your existing Email Templates information.
	//
	// GET /templates/email/list
	ListEmailTemplates(ctx context.Context, params ListEmailTemplatesParams) (*ListEmailTemplatesResponse, error)
	// ReplaceCatalogItem implements replaceCatalogItem operation.
	//
	// Replace catalog item.
	//
	// PUT /catalogs/{catalog_name}/items/{item_id}
	ReplaceCatalogItem(ctx context.Context, req *ReplaceCatalogItemRequest, params ReplaceCatalogItemParams) (*CatalogItemOperationResponse, error)
	// UpdateContentBlock implements updateContentBlock operation.
	//
	// Update a Content Block on the Braze dashboard.
	//
	// POST /content_blocks/update
	UpdateContentBlock(ctx context.Context, req *UpdateContentBlockRequest) (UpdateContentBlockRes, error)
	// UpdateEmailTemplate implements updateEmailTemplate operation.
	//
	// Update an Email Template on the Braze dashboard.
	//
	// POST /templates/email/update
	UpdateEmailTemplate(ctx context.Context, req *UpdateEmailTemplateRequest) (*UpdateEmailTemplateResponse, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
